### ISSUE TITLE
Disconnect every few seconds

### ISSUE THREAD

**Issue by jflefebvre06** [Jutta-Proto/protocol-bt-cpp#13]
Hello,
Thanks a lot for the job, perfectly works with my Jura **S80**, the only problem I have is it disconnect every few seconds
![image](https://github.com/Jutta-Proto/protocol-bt-cpp/assets/2685607/c85bc2fb-a175-42b1-86cc-3f47b932d23e)

Any idea ?

I use atom bluetooth proxy

```yaml
substitutions:
  name: atom-bluetooth-proxy
  board: m5stack-atom
  mac: 0d350c

esphome:
  name: ${name}
  name_add_mac_suffix: true

esp32:
  board: ${board}
  framework:
    type: esp-idf

# Enable Home Assistant API
api:

# Enable logging
logger:

ota:

improv_serial:

# captive_portal:

bluetooth_proxy:
  active: true

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: ${name}-${mac}.local

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true
```
